name: Deploy Workflow

on:
  label:
    types:
      - created

jobs:
  deployszia:
    name: deploy to github sites
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: PHP Runner
        uses: franzliedke/gh-action-php@0.2.0
